### PR TITLE
Removing Tyler's suggestion. I don't trust him.

### PR DESCRIPTION
**Pull request by dckesler**

### CODE REVIEW

**Comment by tylermcginnis** [comment]
+1

**Comment by tylermcginnis** [comment]
c7358e161859b0a65c09fef0e3996c13

**Review by jacob-israel-turner — APPROVED** [review]

**Review by eanplatter — APPROVED** [review]
This is important work @dckesler

**Review by tylermcginnis — APPROVED** [review]

**Review by jergason — APPROVED** [review]

**Comment by jergason** [comment]
please sign our CLA as required by our contributing.md

**Comment by dckesler** [comment]
I warned you https://twitter.com/jergason/status/852023626186473473

**Pull request closed without merging**
